-- Sample opportunities for Kathmandu students (MVP seed data)
-- Run after opportunities.sql. Safe to re-run — skips if titles already exist.

insert into public.opportunities (
  title, type, description, organizer, registration_link, deadline,
  start_date, end_date, location, is_online, subject_area,
  grade_requirements, cost, time_commitment, skills_gained,
  difficulty_level, tags
)
select * from (values
  (
    'Kathmandu Science Olympiad',
    'Competition',
    'A city-wide science competition for secondary students. Test your knowledge in physics, chemistry, and biology through written rounds and a practical lab challenge.',
    'Nepal Science Foundation',
    'https://example.com/kathmandu-science-olympiad',
    (current_date + interval '45 days')::date,
    (current_date + interval '60 days')::date,
    (current_date + interval '60 days')::date,
    'Kathmandu, Nepal',
    false,
    'Science',
    'Grade 9–12, IGCSE, AS/A Level',
    'Free',
    '2–3 hours on competition day; 2 weeks prep recommended',
    'Scientific reasoning, lab skills, problem solving',
    'Intermediate',
    array['science', 'competition', 'STEM', 'portfolio']
  ),
  (
    'Model UN Kathmandu Chapter',
    'Club',
    'Weekly Model United Nations sessions where students debate global issues, draft resolutions, and build public speaking confidence. Great for leadership and humanities portfolios.',
    'Kathmandu MUN Society',
    'https://example.com/kathmandu-mun',
    (current_date + interval '14 days')::date,
    (current_date + interval '21 days')::date,
    null,
    'Jhamsikhel, Lalitpur',
    false,
    'Social Studies',
    'Grade 10–12',
    'NPR 500/month',
    '2 hours per week',
    'Public speaking, diplomacy, research, leadership',
    'Beginner',
    array['debate', 'leadership', 'humanities', 'MUN']
  ),
  (
    'Intro to Python for Students',
    'Workshop',
    'A beginner-friendly online workshop covering Python basics, simple projects, and how coding skills strengthen university applications.',
    'Code for Nepal',
    'https://example.com/python-workshop',
    (current_date + interval '10 days')::date,
    (current_date + interval '17 days')::date,
    (current_date + interval '24 days')::date,
    'Online',
    true,
    'Technology',
    'Grade 9 and above',
    'Free',
    '3 sessions × 1.5 hours',
    'Programming, logical thinking, project building',
    'Beginner',
    array['coding', 'python', 'online', 'technology']
  ),
  (
    'Community Clean-Up Volunteer Drive',
    'Volunteering',
    'Join a weekend river-side clean-up in Kathmandu. Document your hours for service sections of your portfolio and CV.',
    'Green Kathmandu Initiative',
    'https://example.com/green-kathmandu',
    (current_date + interval '7 days')::date,
    (current_date + interval '14 days')::date,
    (current_date + interval '14 days')::date,
    'Bagmati River, Kathmandu',
    false,
    'Environment',
    'Open to all secondary students',
    'Free',
    'Half day (4 hours)',
    'Teamwork, community service, environmental awareness',
    'Beginner',
    array['volunteering', 'service', 'environment', 'CV']
  ),
  (
    'British Council IELTS Prep Workshop',
    'Workshop',
    'Prepare for IELTS with tips on reading, writing, listening, and speaking. Useful if you plan to study abroad.',
    'British Council Nepal',
    'https://example.com/british-council-ielts',
    (current_date + interval '20 days')::date,
    (current_date + interval '28 days')::date,
    (current_date + interval '35 days')::date,
    'British Council, Kathmandu',
    false,
    'English',
    'Grade 11–12, AS/A Level',
    'NPR 1,500',
    '4 weekly sessions',
    'Academic English, exam strategy, communication',
    'Intermediate',
    array['IELTS', 'english', 'study abroad', 'workshop']
  ),
  (
    'Young Entrepreneurs Bootcamp',
    'Summer Program',
    'A one-week intensive program on business ideas, pitching, and basic finance. Teams present a mini startup concept at the end.',
    'Nepal Entrepreneurship Hub',
    'https://example.com/ye-bootcamp',
    (current_date + interval '30 days')::date,
    (current_date + interval '90 days')::date,
    (current_date + interval '97 days')::date,
    'Patan, Lalitpur',
    false,
    'Business',
    'Grade 10–12',
    'NPR 3,000 (scholarships available)',
    '1 week full-time',
    'Entrepreneurship, teamwork, presentation, business basics',
    'Intermediate',
    array['business', 'leadership', 'summer program', 'projects']
  ),
  (
    'Kathmandu Mathematics Challenge',
    'Competition',
    'Solve challenging math problems in algebra, geometry, and number theory. Top scorers receive certificates useful for academic portfolios.',
    'Nepal Math Society',
    'https://example.com/math-challenge',
    (current_date + interval '25 days')::date,
    (current_date + interval '40 days')::date,
    (current_date + interval '40 days')::date,
    'Online',
    true,
    'Mathematics',
    'Grade 9–12, IGCSE, AS/A Level',
    'Free',
    '2 hours exam + optional prep',
    'Mathematical reasoning, competition experience',
    'Advanced',
    array['math', 'competition', 'academic', 'STEM']
  ),
  (
    'Hospital Shadowing Internship (Intro)',
    'Internship',
    'A structured 5-day introduction to healthcare settings for students exploring medicine. Observation only — no clinical work.',
    'Kathmandu Medical College Outreach',
    'https://example.com/med-shadow',
    (current_date + interval '35 days')::date,
    (current_date + interval '50 days')::date,
    (current_date + interval '55 days')::date,
    'Kathmandu',
    false,
    'Medicine',
    'Grade 11–12, AS/A Level only',
    'NPR 2,000',
    '5 half-days',
    'Healthcare exposure, professionalism, career insight',
    'Intermediate',
    array['medicine', 'internship', 'career', 'health']
  ),
  (
    'Digital Art & Design Portfolio Lab',
    'Workshop',
    'Learn basics of digital illustration and layout design. Leave with 2–3 portfolio pieces for creative and design-focused applications.',
    'ArtLab Kathmandu',
    'https://example.com/artlab',
    (current_date + interval '12 days')::date,
    (current_date + interval '19 days')::date,
    (current_date + interval '26 days')::date,
    'Online',
    true,
    'Arts',
    'Grade 9 and above',
    'NPR 800',
    '3 sessions × 2 hours',
    'Digital art, design thinking, portfolio pieces',
    'Beginner',
    array['art', 'creative', 'design', 'online']
  ),
  (
    'AS Level Physics Masterclass',
    'Workshop',
    'Focused revision sessions on mechanics and electricity for AS Level students, led by experienced tutors.',
    'Cambridge Prep Nepal',
    'https://example.com/as-physics',
    (current_date + interval '8 days')::date,
    (current_date + interval '15 days')::date,
    (current_date + interval '22 days')::date,
    'Baneshwor, Kathmandu',
    false,
    'Science',
    'AS Level students',
    'NPR 1,200',
    '3 sessions × 2 hours',
    'Physics concepts, exam technique, problem solving',
    'Advanced',
    array['physics', 'AS Level', 'academic', 'revision']
  )
) as v(
  title, type, description, organizer, registration_link, deadline,
  start_date, end_date, location, is_online, subject_area,
  grade_requirements, cost, time_commitment, skills_gained,
  difficulty_level, tags
)
where not exists (
  select 1 from public.opportunities o where o.title = v.title
);
